/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import Model.User;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Ali
 */

public class FormPanel extends javax.swing.JPanel {

    /**
     * Creates new form FormPanel
     */
    private JPanel bottomPanel;
    public FormPanel(JPanel bottomPanel) {
        initComponents();
        this.bottomPanel = bottomPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GenderGroup = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jMainlabel3 = new javax.swing.JLabel();
        jFirstNameLablel3 = new javax.swing.JLabel();
        jLastNameLabel3 = new javax.swing.JLabel();
        Photo = new javax.swing.JLabel();
        jEmailLabel3 = new javax.swing.JLabel();
        jFirstNametext3 = new javax.swing.JTextField();
        jLastNameText = new javax.swing.JTextField();
        jAgeText = new javax.swing.JTextField();
        jEmailText = new javax.swing.JTextField();
        jSubmitButton = new javax.swing.JButton();
        jAgeLabel4 = new javax.swing.JLabel();
        messageText = new javax.swing.JTextField();
        Pateinttypelabel = new javax.swing.JLabel();
        PatientTypeComboBox = new javax.swing.JComboBox<>();
        Genderlabel = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        messagelabel = new javax.swing.JLabel();
        UploadPhotoButton = new javax.swing.JButton();
        jLabel = new javax.swing.JLabel();

        jPanel4.setBackground(new java.awt.Color(0, 0, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jMainlabel3.setBackground(new java.awt.Color(0, 0, 0));
        jMainlabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jMainlabel3.setForeground(new java.awt.Color(255, 255, 255));
        jMainlabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMainlabel3.setText("Patient Registration Form");
        jMainlabel3.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        jFirstNameLablel3.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jFirstNameLablel3.setForeground(new java.awt.Color(255, 255, 255));
        jFirstNameLablel3.setText("FirstName:");

        jLastNameLabel3.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLastNameLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLastNameLabel3.setText("LastName:");

        Photo.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        Photo.setForeground(new java.awt.Color(255, 255, 255));
        Photo.setText("Photo:");

        jEmailLabel3.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jEmailLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jEmailLabel3.setText("Email:");

        jFirstNametext3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFirstNametext3ActionPerformed(evt);
            }
        });

        jLastNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLastNameTextActionPerformed(evt);
            }
        });

        jAgeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAgeTextActionPerformed(evt);
            }
        });
        jAgeText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jAgeTextKeyPressed(evt);
            }
        });

        jEmailText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEmailTextActionPerformed(evt);
            }
        });

        jSubmitButton.setBackground(new java.awt.Color(204, 204, 204));
        jSubmitButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jSubmitButton.setText("Submit");
        jSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubmitButtonActionPerformed(evt);
            }
        });

        jAgeLabel4.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jAgeLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jAgeLabel4.setText("Age:");

        messageText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messageTextActionPerformed(evt);
            }
        });

        Pateinttypelabel.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        Pateinttypelabel.setForeground(new java.awt.Color(255, 255, 255));
        Pateinttypelabel.setText("Pateint Type:");

        PatientTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Heart Patient", "Diabetes Patient", "Checkup Patient", " " }));
        PatientTypeComboBox.setSelectedIndex(-1);
        PatientTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientTypeComboBoxActionPerformed(evt);
            }
        });

        Genderlabel.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        Genderlabel.setForeground(new java.awt.Color(255, 255, 255));
        Genderlabel.setText("Gender:");

        GenderGroup.add(jRadioButton1);
        jRadioButton1.setText("Male");
        jRadioButton1.setActionCommand("MALE USER\n");

        GenderGroup.add(jRadioButton2);
        jRadioButton2.setText("Female");
        jRadioButton2.setActionCommand("FEMALE USER\n");

        GenderGroup.add(jRadioButton3);
        jRadioButton3.setText("Not Preffered");
        jRadioButton3.setActionCommand("OTHER USER\n");

        messagelabel.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        messagelabel.setForeground(new java.awt.Color(255, 255, 255));
        messagelabel.setText("Message:");

        UploadPhotoButton.setBackground(new java.awt.Color(204, 204, 204));
        UploadPhotoButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UploadPhotoButton.setText("Upload Photo");
        UploadPhotoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UploadPhotoButtonActionPerformed(evt);
            }
        });

        jLabel.setText("jLabel");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jMainlabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(jSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(307, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jAgeLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jAgeText, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jFirstNameLablel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFirstNametext3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(Genderlabel)
                                .addGap(27, 27, 27))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(messagelabel)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(messageText)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton1)
                                    .addComponent(jRadioButton2)
                                    .addComponent(jRadioButton3))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(Pateinttypelabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PatientTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(148, 148, 148))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel)
                        .addGap(239, 239, 239))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jEmailLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jEmailText, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLastNameLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Photo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(UploadPhotoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jMainlabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFirstNameLablel3)
                            .addComponent(jFirstNametext3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLastNameLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jAgeLabel4))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jEmailLabel3)
                                        .addComponent(jEmailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jAgeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(messageText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(messagelabel)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Pateinttypelabel)
                        .addComponent(PatientTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Genderlabel)
                            .addComponent(jRadioButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton2)
                        .addGap(4, 4, 4)
                        .addComponent(jRadioButton3)
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Photo)
                            .addComponent(UploadPhotoButton))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel)
                        .addGap(20, 20, 20)))
                .addComponent(jSubmitButton)
                .addContainerGap(169, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jFirstNametext3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFirstNametext3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFirstNametext3ActionPerformed

    private void jEmailTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEmailTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEmailTextActionPerformed

    private void jSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubmitButtonActionPerformed
        // TODO add your handling code here:
         if (isFormValid()) {
        User newUser = new User();
        
        newUser.setFirst_name(jFirstNametext3.getText());
        newUser.setLast_name(jLastNameText.getText());
        newUser.setAge(jAgeText.getText());
        newUser.setEmail(jEmailText.getText());
        newUser.setMessage(messageText.getText());
        newUser.setPatient_Type(PatientTypeComboBox.getSelectedItem().toString());
        newUser.setGender(GenderGroup.getSelection().getActionCommand());
        newUser.setPhoto(jLabel.getIcon());  
        ViewPanel newViewPanel = new ViewPanel(newUser);
        bottomPanel.add(newViewPanel);
        CardLayout layout = (CardLayout) bottomPanel.getLayout();
        layout.next(bottomPanel);
    }
         else{
        JOptionPane.showMessageDialog(this, "Please fill in all required fields.", "Error", JOptionPane.ERROR_MESSAGE);
    }
        
    }//GEN-LAST:event_jSubmitButtonActionPerformed
private boolean isFormValid() {
    // Perform form validation, checking if any required fields are empty
    if (jFirstNametext3.getText().isEmpty() ||
        jLastNameText.getText().isEmpty() ||
        jAgeText.getText().isEmpty() ||
        jEmailText.getText().isEmpty() ||
        PatientTypeComboBox.getSelectedItem() == null ||
        GenderGroup.getSelection() == null||
        jLabel.getIcon()== null) {
        return false;
    }
    
    String ageText = jAgeText.getText();
    try {
        int age = Integer.parseInt(ageText);
        // Add any additional age validation logic here (e.g., age >= 0)
    } catch (NumberFormatException e) {
        // Age is not a valid number
        return false;
    }

    // Add more conditions to validate other fields if needed

    return true;
}
    private void jLastNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLastNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLastNameTextActionPerformed

    private void jAgeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAgeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAgeTextActionPerformed

    private void messageTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messageTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_messageTextActionPerformed

    private void PatientTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientTypeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PatientTypeComboBoxActionPerformed

    private void UploadPhotoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UploadPhotoButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser file = new JFileChooser();
if (file.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
try {
          BufferedImage img = ImageIO.read(file.getSelectedFile());
    Image edited_img = img.getScaledInstance(60, 80, Image.SCALE_SMOOTH);
          if (edited_img!= null) {
          ImageIcon icon = new ImageIcon(edited_img);
           jLabel.setIcon(icon);
         } else 
          {
throw new Exception();
}
} catch (Exception ex) {
}
}

    }//GEN-LAST:event_UploadPhotoButtonActionPerformed

    private void jAgeTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jAgeTextKeyPressed
        // TODO add your handling code here:
        try{
            int age = Integer.parseInt(jAgeText.getText());
            jAgeText.setForeground(Color.black);
        }
        catch(Exception e){
             jAgeText.setForeground(Color.red);
        }
    }//GEN-LAST:event_jAgeTextKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GenderGroup;
    private javax.swing.JLabel Genderlabel;
    private javax.swing.JLabel Pateinttypelabel;
    private javax.swing.JComboBox<String> PatientTypeComboBox;
    private javax.swing.JLabel Photo;
    private javax.swing.JButton UploadPhotoButton;
    private javax.swing.JLabel jAgeLabel4;
    private javax.swing.JTextField jAgeText;
    private javax.swing.JLabel jEmailLabel3;
    private javax.swing.JTextField jEmailText;
    private javax.swing.JLabel jFirstNameLablel3;
    private javax.swing.JTextField jFirstNametext3;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLastNameLabel3;
    private javax.swing.JTextField jLastNameText;
    private javax.swing.JLabel jMainlabel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JButton jSubmitButton;
    private javax.swing.JTextField messageText;
    private javax.swing.JLabel messagelabel;
    // End of variables declaration//GEN-END:variables
}
